- name: Run database
  docker_container:
    name: mydatabase
    image: blueph0enix/my-database:1.0
    state: started
    pull: true
    restart_policy: always
    networks:
      - name: app-network
    env:
      POSTGRES_DB: "{{ db_name }}"
      POSTGRES_USER: "{{ db_user }}"
      POSTGRES_PASSWORD: "{{ db_password }}"