name: CI devops 2025

on:
  # on veut lancer ce job sur les push et pull request des branches main et develop
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      # récupère le code du repo pour que le runner puisse y accéder
      - uses: actions/checkout@v4

      # installe le JDK 21 nécessaire pour builder et tester l'application Spring Boot
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # build + exécute les tests unitaires et d'intégration (Testcontainers lance un Postgres temporaire)
      - name: Build and test with Maven
        run: mvn clean verify --file ./simpleapi/pom.xml

  build-and-push:
    needs: test-backend
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simpleapi
          push: true
          tags: blueph0enix/simpleapi:1.0

      - name: Build and database
        uses: docker/build-push-action@v6
        with:
          context: ./Database
          push: true
          tags: blueph0enix/my-database:1.0

      - name: Build and push httpd
        uses: docker/build-push-action@v6
        with:
          context: ./HttpServer
          push: true
          tags: blueph0enix/my-httpd:1.0

      - name: Build and push front
        uses: docker/build-push-action@v6
        with:
          context: ./front
          push: true
          tags: blueph0enix/my-front:1.0


  deploy:
    needs: build-and-push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Ansible
        run: |
          pip install ansible
          ansible-galaxy collection install community.docker

      - name: Set up SSH and Ansible Vault
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          VAULT_PASS: ${{ secrets.ANSIBLE_VAULT_PASSWORD }}
        run: |
          mkdir -p ~/.ssh
          printf "%s\n" "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 400 ~/.ssh/deploy_key
        
          mkdir -p ~/.ansible
          printf "%s\n" "$VAULT_PASS" > ~/.ansible/vault_pass
          chmod 400 ~/.ansible/vault_pass

          ssh-keyscan -H thomas.danjou.takima.school >> ~/.ssh/known_hosts

      - name: Run playbook in Docker
        run: |
          ansible-playbook -i inventories/setup.yml playbook.yml
          -e ansible_ssh_private_key_file=~/.ssh/deploy_key